name: massanotif
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  dio: ^4.0.6
  hive: ^2.2.3
  isar: ^3.0.5
  sqflite: ^2.2.3

dev_dependencies:
  build_runner: ^2.3.3
  isar_generator: ^3.0.5
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
